name: Deploy to Pre

on:
  push:
    tags:
    - 'prod'

jobs:

  build:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Deploy to prod
      env:
        LONG_SHA: ${{ github.sha }}
      run: |
        SHORT_SHA="${LONG_SHA:0:7}"
        echo "Deploying ${SHORT_SHA} => prod"
