name: Deploy to Dev

on:
  push:
    tags:
    - 'dev'

jobs:

  build:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Deploy to dev
      run: |
        echo "Deploying to dev"
